/# Window Rules

windowrule=isfloating:1,appid:xdg-desktop-portal-gtk,title:打开本地仓库
windowrule=isfloating:1,appid:xdg-desktop-portal-gtk,title:打开文件

windowrule=isfloating:1,title:Translate
windowrule=width:800,height:900,title:Translate

windowrule=globalkeybinding:ctrl+alt-o,appid:com.obsproject.Studio
windowrule=globalkeybinding:ctrl+alt-n,appid:com.obsproject.Studio
windowrule=scratchpad_width:1500,scratchpad_height:900,appid:^com.obsproject.Studio$
# windowrule=isopensilent:1,appid:com.obsproject.Studio

windowrule=noswallow:1,appid:flameshot
windowrule=isfullscreen:1,appid:flameshot
windowrule=animation_type_open:none,appid:flameshot
windowrule=animation_type_close:none,appid:flameshot
# windowrule=animation_type_close:none,appid:Sxiv

windowrule=isfloating:1,width:1500,height:900,appid:pot,title:Recognize
windowrule=animation_type_open:none,animation_type_close:none,isnoshadow:1,isnoradius:1,isnoborder:1,appid:^wps$,title:^wps$
windowrule=force_maximize:1,appid:^wpsoffice$

windowrule=isfloating:1,title:图片查看器
windowrule=isfloating:1,title:预览
windowrule=isfloating:1,title:图片查看
windowrule=isfloating:1,title:选择文件
windowrule=isfloating:1,title:打开文件

windowrule=animation_type_open:zoom,title:图片查看器
windowrule=animation_type_open:zoom,title:图片查看
windowrule=animation_type_open:zoom,title:选择文件
windowrule=animation_type_open:zoom,title:打开文件

windowrule=tags:9,appid:QQ
windowrule=tags:9,appid:wechat
windowrule=animation_type_open:none,nofadein:1,title:wechat
windowrule=animation_type_close:none,nofadeout:1,title:wechat
windowrule=tags:9,appid:discord

windowrule=isfloating:1,isoverlay:1,isnoborder:1,isunglobal:1,width:280,height:200,offsetx:9999,offsety:9999,appid:mpv,title:video0 - mpv

# layer rule
layerrule=noblur:1,noanim:1,layer_name:selection
layerrule=noblur:1,noanim:1,layer_name:quickshell
layerrule=noblur:1,noanim:1,layer_name:quickshell:popout
layerrule=noblur:1,noanim:1,layer_name:dms
layerrule=noblur:1,noanim:1,layer_name:dms:.*
layerrule=noblur:1,noanim:1,layer_name:dimland_layer
layerrule=noanim:1,noblur:1,noshadow:1,layer_name:hyprpicker
layerrule=noanim:1,layer_name:showkeys
