#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "Ricardo"
email = "ricardoryn1317@gmail.com"

[ui]
default-command = "log"
editor = "nvim"
diff-editor = ["nvim", "-c", "DiffEditor $left $right $output"]
diff-instructions = false
merge-editor = ["nvim", "-c", "MergeEditor $base $left $right $output $path"]

[git]
fetch = ["origin", "upstream"]
private-commits = '''description(glob:'WIP:*')'''

[lazyjj]
highlight-color = "#cccccc"
diff-tool = "delta"

[template-aliases]
"format_short_signature(signature)" = "signature.name()"
"format_timestamp(timestamp)" = "timestamp.ago()"

[aliases]
l = ["log", "-r", "::", "-n", "20"]

[colors]
"diff removed token" = { bg = "#442726", underline = false }
"diff added token" = { bg = "#26332c", underline = false }
"diff context" = { dim = true }
